# Generated by Django 4.2.3 on 2023-07-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.items'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.table'),
            preserve_default=False,
        ),
    ]
