# Generated by Django 4.2.3 on 2023-07-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
