# Generated by Django 4.2.3 on 2023-07-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_table_alter_orderdetail_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(),
        ),
    ]
