# Generated by Django 4.2.3 on 2023-07-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('COM', 'Complete')], default='PEN', max_length=3),
        ),
    ]
